language: objective-c

branches:
  only:
    - master

xcode_project: Permission.xcodeproj
xcode_scheme: PermissionTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

script:
  - xcodebuild test -project Permission.xcodeproj -scheme PermissionTests -destination "platform=iOS Simulator,name=iPhone 6s"
